name: fuzzy
version: 0.4.1

description: >
  Fuzzy search in Dart. Initially a code conversion, subset of Fuse.js.
homepage: https://github.com/comigor/fuzzy

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  stringr: ^1.0.0

dev_dependencies:
  test: ^1.24.6-nullsafety
  pedantic: ^1.11.1-nullsafety
