on: [pull_request, push]

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@master
    - name: Run tests
      uses: comigor/actions/dart-test@master
  deploy:
    needs: test
    runs-on: ubuntu-latest    
    if: contains(github.ref, 'master')
    steps:    
    - name: Clone repository
      uses: actions/checkout@master          
    - name: Publish to pub.dev
      uses: comigor/actions/pub-publish@master      
      env:
        PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
